thorsten/phpMyFAQ

phpmyfaq/ajaxservice.php
phpmyfaq/inc/PMF/Export/Pdf.php
phpmyfaq/inc/PMF/Faq.php
phpmyfaq/inc/PMF/Helper/Search.php
phpmyfaq/inc/PMF/Sitemap.php

These changes use Parsedown if Markdown is enabled to generate the Output for Pdf and Sitemap generation.

Enable Parsedown in Pdf and Sitemap generation

---

phpmyfaq/inc/Bootstrap.php

@thorsten requested this pull request.
It consists of patches automatically generated for this project on Scrutinizer:
https://scrutinizer-ci.com/g/thorsten/phpMyFAQ/

Scrutinizer Auto-Fixes

---

scripts/moveVendors.sh

For https://github.com/thorsten/phpMyFAQ/issues/1197

---

phpmyfaq/admin/record.edit.php

Fix label for change history

---

documentation/documentation.md

typo ` (s`

---

phpmyfaq/setup/assets/twig/database.twig
phpmyfaq/setup/index.php

This doesn't fix it fully. The installation form can't be submitted. Investigate, please.

For #1280: install with SQLite as the only RDBMS

---

phpmyfaq/assets/template/default/indexLogin.tpl
phpmyfaq/assets/template/default/indexMaintenance.tpl
phpmyfaq/assets/template/default/indexNewUser.tpl
phpmyfaq/assets/template/default/indexPassword.tpl

Some template files have not been adapted to the new logo path in PR #1318 . Here are the remaining adaptions.

Moved the logo for the application from the assets/img directory (2)

---

phpmyfaq/_nginx.conf

fixes: https://github.com/thorsten/phpMyFAQ/issues/939

added end brace

---

phpmyfaq/admin/record.questions.php

Removed duplicated "delete" text

---

phpmyfaq/assets/themes/default/templates/index.html

Fix a few errors in the index.html template:
\<li> parent must be \<ul>, \<ol> or \<menu>
missing \</ul> from \<header> section

Fix a few errors in the index.html template:

---

phpmyfaq/admin/ajax.group.php
phpmyfaq/admin/category.add.php
phpmyfaq/admin/category.edit.php
phpmyfaq/admin/category.main.php
phpmyfaq/admin/record.edit.php
phpmyfaq/admin/record.show.php
phpmyfaq/lang/language_en.php
phpmyfaq/setup/update.php
phpmyfaq/src/PMF/Category.php
phpmyfaq/src/PMF/Faq.php
phpmyfaq/src/PMF/Perm/Medium.php

Hi Thorsten,
Here's the updated PR for the category & group restriction feature in the admin page. I've also added the suggestions you've mentioned on the previous PR. Thanks!

added category & group restrictons.

---

phpmyfaq/admin/assets/scss/style.scss
phpmyfaq/admin/footer.php
phpmyfaq/admin/header.php
phpmyfaq/src/PMF/Helper/Administration.php

May need further editing.
Some of the css is from 2.9

Modifications to make the admin menu useable

---

phpmyfaq/admin/category.main.php
phpmyfaq/admin/record.edit.php
phpmyfaq/lang/language_de.php

improvement: quick add record 2.9

---

phpmyfaq/admin/category.main.php
phpmyfaq/admin/record.edit.php

Improvement: quick add record 3.0 

---

phpmyfaq/assets/template/default/contact.tpl

changed itunes-svg to https

---

scripts/moveVendors.sh

fixed composer moveVendors script

---

phpmyfaq/src/phpMyFAQ/Installer.php

Installation lief dann sauber durch.

fixed Ldap DbQuery bug in Installer

---

phpmyfaq/admin/export.file.php

The current export, exports all languages. It makes more sense to export just the language you have selected.

Export in the language the user selected

---

README.md

Update docker hub links in the readme

Update docker hub links

---

phpmyfaq/admin/report.export.php
phpmyfaq/admin/report.view.php

fixed the date bug in report.view & report.export for branch 2.9

fixed report date bug

---

phpmyfaq/src/phpMyFAQ/Instance/Database/Mysqli.php

Mysqli Instance created Sections

---

phpmyfaq/inc/PMF/User.php

fixed display errors from debug_backtrace

---

phpmyfaq/admin/group.php

fixed group right assignement

---

Gruntfile.js
phpmyfaq/assets/themes/default/scss/floating-labels.scss
phpmyfaq/assets/themes/default/templates/indexLogin.html

The paths was fixed, but it was not styled correctly. Its nice that you are using Bootstrap 4, so I used the following Example for a more "fancy" Front-Login Page. 
https://getbootstrap.com/docs/4.2/examples/floating-labels/

Improve Style of indexLogin Template

---

phpmyfaq/lang/language_de.php
phpmyfaq/lang/language_en.php

* Synchronized vars German <<=>> English and translated new vars for each language
* removed duplicates
* cloned and translates "blocks names" (lines starting with comment //), so that the same blocks and vars are in both files
Note: I used DeepL for german<->english translation... I hope the translation's not too bad.

revised DE & EN translations

---

.gitignore
phpmyfaq/lang/language_en.php
phpmyfaq/lang/language_es.php

* updated to latest vars (v3.1.0-alpha - 2020-03-27 by Thorsten)
* replicated vars blocks from language_de.php
* revised all translations for coloquial spanish (Spain)

Updated spanish translations

---

phpmyfaq/src/phpMyFAQ/Export/Html5.php

Adds an ID attribute of "entry-####" (based on the solution_id) to each entry, for easy anchor linking.

Add "entry-####" ID attribute to each h2

---

scripts/langEditor.php

Creating a way to easily translate the files. When translating, it was really hard to know which strings were untranslated.
If it didn't fit in the project standards, understandable. I created it to help me to improve Portuguese translation and thought it might be useful.

Creating a simple language editor

---

phpmyfaq/lang/language_ja.php

Hello, maintainers.
Japanese translation file `lang/language_ja.php` was abandoned since v2.9.0-alpha.
I sync some keys from `language_en.php` and translate it.
Thanks.

Added Japanese translation.

---

phpmyfaq/lang/language_fr.php

- language_fr.php has been refactored to follow language_en.php structure, it will be easier to update that file in future updates.
- Completely reviewed the existing french translation for better consistency and precision. It may not be perfect, but it is largely improved.
- Completed missing translations (except LDAP settings that doesn't make more sense in French than in English)
Thanks a lot to the original translators for their huge work :)

Complete review of language_fr.php

---

phpmyfaq/src/phpMyFAQ/Category.php

corrected an issue where no categories are being returned when using MS SQL Server as a database (#2137)

fix: corrected an issue where no categories are being returned 

---

phpmyfaq/index.php

Hi Thorsten, 
a little idea, which I just included into my phpmyfaq-installation. Maybe it would be interesting for everybody. 
I included a variable for own-created templates, which will show the current year, e.g. for copyright notices. What do you think?

Added currentYear to main-template

---

composer.json
composer.lock
phpmyfaq/admin/index.php
phpmyfaq/admin/twofactor.php
phpmyfaq/admin/user.php
phpmyfaq/api.service.php
phpmyfaq/assets/themes/default/templates/twofactor.php
phpmyfaq/assets/themes/default/templates/ucp.html
phpmyfaq/index.php
phpmyfaq/lang/language_de.php
phpmyfaq/lang/language_en.php
phpmyfaq/login.php
phpmyfaq/setup/update.php
phpmyfaq/src/phpMyFAQ/Instance/Database/Mysqli.php
phpmyfaq/src/phpMyFAQ/Instance/Database/Pgsql.php
phpmyfaq/src/phpMyFAQ/Instance/Database/Sqlite3.php
phpmyfaq/src/phpMyFAQ/Instance/Database/Sqlsrv.php
phpmyfaq/src/phpMyFAQ/Link.php
phpmyfaq/src/phpMyFAQ/Twofactor.php
phpmyfaq/src/phpMyFAQ/User/CurrentUser.php
phpmyfaq/src/phpMyFAQ/User/UserAuthentication.php
phpmyfaq/src/phpMyFAQ/User/UserData.php
phpmyfaq/ucp.php

Take a look at this. This adds support for two-factor-authentification. I had some problems with implementating my 'old' code into your new UserAuthentification-Class, but should work like this. 
I used the lib we talked about "RobThree/TwoFactorAuth". I added some linkings in composer.json and composer.lock. 
What do you think about this?
I needed a bit time to dive into your code, but in the end, it was a lot of fun coding some things with php. 
Closes #1090

Twofactor-Authentification

---

phpmyfaq/admin/index.php
phpmyfaq/admin/twofactor.php
phpmyfaq/assets/themes/default/templates/twofactor.html
phpmyfaq/index.php
phpmyfaq/login.php
phpmyfaq/src/phpMyFAQ/User/CurrentUser.php
phpmyfaq/src/phpMyFAQ/User/UserAuthentication.php

Hi Thorsten, 
I wrote you an email a few hours ago. I improved 2FA-code again a bit. Now it's working perfectly together with ver3.2

Improved code for Using 2FA with Ver3.2

---

phpmyfaq/admin/record.add.php

Ist mir nur gerade aufgefallen beim "Spielen" ....

fix: missing Translation class

---

phpmyfaq/assets/themes/default/templates/ucp.html
phpmyfaq/src/phpMyFAQ/User/TwoFactor.php

I promise you: This will be my last pull request having to do with two-factor-authentication. 
This will show the title of the FAQ in the authenticator-app instead of "phpMyFAQ". This will prevent any misunderstandings.

My last PR regarding 2FA

---

phpmyfaq/lang/language_de.php
phpmyfaq/lang/language_en.php
phpmyfaq/setup/update.php
phpmyfaq/src/phpMyFAQ/Export/Html5.php
phpmyfaq/src/phpMyFAQ/Export/Pdf/Wrapper.php
phpmyfaq/src/phpMyFAQ/Setup/Installer.php

Hi Thorsten, 
this is my first one. Thank's for waiting with releasing the 3.2-final-version. I think, I'll be done at tuesday next week at lastet.
This will add an option to show/hide the mail address in export-files (Pdf and HTML5).
Maybe you just have to edit the update file and adjust it to the release version-number.
Thank's again!

Feat: Option to hide mail address in export-files

---

phpmyfaq/admin/export.main.php

This would open all inline streams in a new tab.
I think, it would bring up more structure.

feat: open inline streams in a new tab.

---

phpmyfaq/src/phpMyFAQ/Search/SearchDatabase.php

Debugging code was removed because it remained.

Refactor: remove debugging code

---

phpmyfaq/admin/record.add.php

Fixed a problem in which the value of active was always set to yes when registering a new FAQ.

Fix: a bug in registering new FAQs

---

phpmyfaq/src/phpMyFAQ/Faq.php

Fixed a bug that caused the FAQ to always go private when updated.

Fix: a bug in updating FAQs

---

phpmyfaq/.htaccess
phpmyfaq/api.php

I noticed two issues while implementing my API function:
- In the .htaccess is a RewriteRule for /api/v2.1/question missing
- In api.php '$this->config' cant be used because it is not a class

Fixes for using API [Adding new question]

---

phpmyfaq/src/phpMyFAQ/Setup/Upgrade.php

s. Discord
Bitte Exceptions prüfen! @thorsten

feat[upgrade]: unpack and verify methods

---

phpmyfaq/admin/api/updates.php
phpmyfaq/admin/assets/js/upgrade.js
phpmyfaq/admin/assets/templates/configuration/upgrade.twig
phpmyfaq/admin/header.php
phpmyfaq/translations/language_de.php
phpmyfaq/translations/language_en.php

Alles getestet, läuft bei mir super. Ich weiß, ob du das so magst.

Upgrade Admin Seite

---

phpmyfaq/src/phpMyFAQ/Configuration.php
phpmyfaq/src/phpMyFAQ/Setup/Upgrade.php

checkFilesystem method
Im Live-Betrieb gestestet. 
Hast du dir das so vorgestellt? Fehlt etwas?

feat: added checkFilesystem method

---

phpmyfaq/index.php
phpmyfaq/src/constants.php

1. Define PMF_LANGUAGE_DIR as constant in constants.php to avoid errors
2. Added Bookmarks-link to control dropdown

Several bug fixes

---

phpmyfaq/admin/assets/src/content/faqs.js
phpmyfaq/admin/record.edit.php
phpmyfaq/api.php
phpmyfaq/translations/language_de.php
phpmyfaq/translations/language_en.php

No # in faq name

---

phpmyfaq/src/phpMyFAQ/Setup/Installer.php

feat: adjust RewriteBase while installing

---

phpmyfaq/src/phpMyFAQ/User/TwoFactor.php

fix: optimize display issuer and label in Authenticator-App

---

phpmyfaq/admin/assets/src/content/faqs.js
phpmyfaq/src/phpMyFAQ/Permission/MediumPermission.php

#1818 - Possible solution?

---

phpmyfaq/src/phpMyFAQ/Database/Mysqli.php
phpmyfaq/src/phpMyFAQ/Database/Pgsql.php
phpmyfaq/src/phpMyFAQ/Database/Sqlite3.php
phpmyfaq/src/phpMyFAQ/Database/Sqlsrv.php
phpmyfaq/src/phpMyFAQ/Session.php
phpmyfaq/src/phpMyFAQ/Setup/Installer.php
phpmyfaq/translations/language_de.php
phpmyfaq/translations/language_en.php

I also deleted the old table "faqmeta" from the Database-files

Function to block browsers from the visitor chart at the dashboard

---

phpmyfaq/src/phpMyFAQ/Session.php
phpmyfaq/src/phpMyFAQ/Setup/Installer.php
phpmyfaq/src/phpMyFAQ/Setup/Update.php
phpmyfaq/translations/language_de.php
phpmyfaq/translations/language_en.php

Deleted old code for blocked statistic browsers

Added BotIgnoreList as configurable value

---

phpmyfaq/admin/assets/src/configuration/configuration.js
phpmyfaq/admin/instances.php
phpmyfaq/admin/login.php
phpmyfaq/admin/user.php
phpmyfaq/assets/src/utils/password.js
phpmyfaq/assets/themes/default/templates/login.html
phpmyfaq/assets/themes/default/templates/ucp.html

Should be all password inputs
Closes #2623 
Happy Christmas!

Added general function for password-view-buttons

---

kubernetes-deploy/01-phpmyfaq-deployment.yaml
kubernetes-deploy/02-phpmyfaq-svc.yaml
kubernetes-deploy/03-phpmyfaq-ingress.yaml

Those files, are samples about how implement deployment, service and ingress manifest for kubernetes environment.

Adding kubernetes manifest samples

---

docs/administration.md

Documentation for CSV Import

---

phpmyfaq/assets/themes/default/templates/faq.html
phpmyfaq/faq.php
phpmyfaq/src/phpMyFAQ/Controller/Administration/AttachmentController.php
phpmyfaq/src/phpMyFAQ/Controller/Administration/CategoryController.php
phpmyfaq/src/phpMyFAQ/Controller/Administration/CommentController.php
phpmyfaq/src/phpMyFAQ/Controller/Administration/ConfigurationController.php
phpmyfaq/src/phpMyFAQ/Controller/Administration/ConfigurationTabController.php
phpmyfaq/src/phpMyFAQ/Controller/Administration/ElasticsearchController.php
phpmyfaq/src/phpMyFAQ/Controller/Administration/ExportController.php
phpmyfaq/src/phpMyFAQ/Controller/Administration/FaqController.php
phpmyfaq/src/phpMyFAQ/Controller/Administration/ImageController.php
phpmyfaq/src/phpMyFAQ/Controller/Administration/InstanceController.php
phpmyfaq/src/phpMyFAQ/Controller/Administration/QuestionController.php
phpmyfaq/src/phpMyFAQ/Controller/Administration/SearchController.php
phpmyfaq/src/phpMyFAQ/Controller/Administration/SessionController.php
phpmyfaq/src/phpMyFAQ/Controller/Administration/StopWordController.php
phpmyfaq/src/phpMyFAQ/Controller/Administration/TagController.php
phpmyfaq/src/phpMyFAQ/Controller/Administration/UpdateController.php
phpmyfaq/src/phpMyFAQ/Controller/Administration/UserController.php
phpmyfaq/src/phpMyFAQ/Helper/FaqHelper.php

Several issues

---

.gitignore
phpmyfaq/admin/assets/src/sessions.js
phpmyfaq/admin/assets/src/statistics.js
phpmyfaq/admin/statistics.sessions.php
phpmyfaq/assets/templates/admin/statistics/sessions.twig

Download sessions as csv-file

---

phpmyfaq/admin/assets/src/content/overview.js
phpmyfaq/admin/record.show.php

Fix several problems with checkboxes in 3.2.4

---

package.json
phpmyfaq/assets/src/utils/cookie-consent.js
phpmyfaq/assets/themes/default/templates/index.html
phpmyfaq/index.php
phpmyfaq/lang/language_de.php
phpmyfaq/lang/language_en.php
phpmyfaq/privacy.php
pnpm-lock.yaml

Update Cookie Consent

---

phpmyfaq/admin/assets/src/user/user-list.js
phpmyfaq/admin/statistics.show.php
phpmyfaq/assets/templates/admin/statistics/statistics.show.twig

Twig sessions

---

phpmyfaq/admin/category.add.php
phpmyfaq/admin/dashboard.php
phpmyfaq/admin/faqs.editor.php
phpmyfaq/assets/templates/admin/content/faq.editor.twig
phpmyfaq/assets/templates/admin/content/stickyfaqs.twig
phpmyfaq/index.php
phpmyfaq/src/phpMyFAQ/Controller/Administration/FaqController.php

- Don't show records if customly ordered sticky faqs-function is deactivated in the configuration
- Corrected some icons
- Don't set all new faqs automatically to sticky
- Minor Bugs with BasicPermission and Medium Permission

Minor bugs

---

phpmyfaq/sitemap.xml.php

Create Translation instance when using sitemap

---

phpmyfaq/add.php
phpmyfaq/src/phpMyFAQ/Configuration.php
phpmyfaq/src/phpMyFAQ/Controller/Administration/ConfigurationTabController.php

Closes #2615
@thorsten Happy Holiday, take a look at this afterwards ;-)

Introduced tool to change main.referenceURL if its changed in configuration

---

phpmyfaq/src/phpMyFAQ/Session.php

https://developers.facebook.com/docs/sharing/webmasters/crawler?locale=de_DE

feat: added Facebook crawlers to botIgnoreList

---

phpmyfaq/add.php
phpmyfaq/ask.php
phpmyfaq/assets/templates/add.twig
phpmyfaq/assets/templates/ask.twig
phpmyfaq/src/phpMyFAQ/Controller/Frontend/QuestionController.php
phpmyfaq/translations/language_de.php
phpmyfaq/translations/language_en.php

This should finally (and hopefully) close #2886 
@thorsten Please review and test it!

Ask-Form for #2886

---

docs/administration.md
docs/usage.md

Added 4.5.1 Batch upload FAQs to Database with CSV files.

administration.md / 5.4.3 Batch upload via phpMyAdmin

---

docs/administration.md

In administration.md I added at 5.2.1 Category Administration a short addition to the first paragraph.
And below that a new paragraph, describing an option on how to use same files multiple times as category images.

Updated administration.md / 5.2.1 Category Administration

---

phpmyfaq/assets/templates/admin/content/faq.editor.twig

fix: do not escape email address

---

phpmyfaq/src/phpMyFAQ/User.php

Beim Testen gleich einen Fehler entdeckt

fix: no ability to create a new category

---

phpmyfaq/admin/assets/src/api/user.js
phpmyfaq/admin/assets/src/user/users.js
phpmyfaq/src/phpMyFAQ/Controller/Administration/UserController.php
phpmyfaq/translations/language_de.php
phpmyfaq/translations/language_en.php

It was not possible to overwrite passwords in the admin user administration and the error messages provided were not correct. These commits have to merged in one together.

fix: improved overwriting passwords

---

phpmyfaq/assets/templates/admin/content/faq.editor.twig
phpmyfaq/translations/language_de.php
phpmyfaq/translations/language_en.php

feat: added alert for private notes over the faq editor

---

phpmyfaq/admin/category.main.php
phpmyfaq/assets/templates/admin/content/category.translate.twig

feat: added functionality to add serp title and description to translated categories (#3120)

---

phpmyfaq/admin/assets/src/user/users.js
phpmyfaq/assets/templates/admin/user/users.twig
phpmyfaq/assets/templates/default/startpage.twig

Buttons rights

---

phpmyfaq/admin/assets/src/group/groups.js
phpmyfaq/assets/templates/admin/user/group.twig

I also improved the groups administration to prevent error messages. Closes #3140

Buttons group administration

---

phpmyfaq/src/phpMyFAQ/Controller/Administration/UserController.php

Es war nicht möglich, neue Users zu erstellen. Das ist der Fix. :)

fix: dont raise errors and let admins create new users

---

phpmyfaq/assets/templates/default/ucp.twig
phpmyfaq/ucp.php

Please merge this as one commit.

Dont show possibility to setup webauthn in ucp if not enabled

---

phpmyfaq/src/phpMyFAQ/Faq/Permission.php

fix: let users edit faqs that are permitted to only one group

---

phpmyfaq/assets/templates/admin/content/category.edit.twig
phpmyfaq/assets/templates/default/show.twig

Please merge this as one commit.

fix: correctly encode some strings in twig
