phpmyfaq/setup/assets/sql/pgsql.sql.php
Bug 1
Int with precision does not work/exist for Postgres, I checked out what this does on https://dev.mysql.com/doc/refman/5.0/en/numeric-type-attributes.html and this seams to have something to do with the 'display width'. I don't know if this is of any use for the MySQL version of the setup script..
Bug 2
The table faqinstances is expected to have a faqinstances_id_seq sequence, so I guess this should be auto-numbering. I changed the field type from int to serial.
=> Fixed 2 errors in the setup for postgresql database

phpmyfaq/inc/PMF/Ldap.php
ldap_set_option expects an integer value to be provided for the option.
This change properly looked up the integer value based on the name of
the constant being passed.
=> Corrects LDAP option bug by retrieving the constant value.

composer.json
Installing from GIT (as per README.md) with new Composer failed, because non-SSL GIT (over git:// and http://) is disabled by default in new Composer. See https://github.com/composer/composer/issues/5475.
=> Removed duplicate entries. Allowed non-SSL GIT access.

composer.json
to allow non-SSL git access with new Composer
=> cherry-pick b12cff25eaa19668a4022ceba6b5fa890e9a60e4 

composer.json
to allow non-SSL git access with new Composer
=> cherry-pick b12cff25eaa19668a4022ceba6b5fa890e9a60e4 adjusted

phpmyfaq/assets/js/setup.js
Enabling SQLite-specific install fields, when installing on a machine that only supports SQLite (and therefore there are no other RDBMS listed).
For https://github.com/thorsten/phpMyFAQ/issues/1194
=> Installing on a machine with SQLite as the only RDBMS

phpmyfaq/setup/assets/sql/sqlsrv.sql.php
Fixed issue #1300 where "DB error: 42000: [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Column, parameter, or variable #11: Cannot specify a column width on data type int." received on setup
=> Removed column width from data type INT

phpmyfaq/login.php, phpmyfaq/register.php
Currently registration is possible even if security.enableRegistration is
disabled.
This commit disables the registration by redirecting to the index page
and also disables the registration link on the login form.
=> consider enableRegistration for registrations

phpmyfaq/admin/news.php
Current browsers display a warning if no valid url is entered into an url field of a form.
On the "Add News" page this happens as well if create a news entry, but do not (want to) specify an url at all.
You have to deleted the "http://" manually before it is possible to save the news entry.
This could be avoided by using the "placeholder" attribute instead of the "value" attribute.
This way, the desired format is shown, but the user is not forced to take any action if no url is desired.
=> Replace default value in url by placeholder

phpmyfaq/artikel.php
If you remove all of the languages bar 1, the "Translate this FAQ" is still shown and attempts to allow the user to do a translation anyway.
Prevent this from happening by hiding the "Translate this FAQ" serverside
=> Hide "Translate this FAQ" if there is only 1 language

phpmyfaq/ajaxservice.php
Similar fix to #1276 but for addquestion instead of addcomment
Patch made on 2.9 but probably applies to 2.10 too
=> Incorrect permission on New Question

phpmyfaq/admin/record.edit.php, phpmyfaq/lang/language_en.php
Users in my organization requested a way to view a FAQ after editing it without having to navigate through the website. I added a "View FAQ" button after the revision number in the Edit view.
=> Added "View FAQ" Button

package.json
This patch fixes a missing node.js dependency issue (possibly inherited from grunt-modernizr->customizr->modernizr tree - may be an upstream issue)
Regardless, allows travis-cl checks to clear successfully
=>  Fix missing node.js dependency - Merge/check first

phpmyfaq/inc/PMF/User/CurrentUser.php
The $logoutTime should not be used in the calculation of the session timestamp and in the check of the last login, but only in the login check function isFailedLastLoginAttempt (). 
Reasons:
1. It is more intuitive if the session timestamp represents the time of the actual login attempt.
2. If it is taken into account in both functions, the time has to elapse twice. This is not obvious to see.
=> FIX: $lockoutTime should be used only once

phpmyfaq/inc/PMF/Search/Resultset.php
When articles are asigned to specific permissions and you specify multiple groups it only uses the first group in the $groupPermission array which is -1.  This results in users not being able to find articles using the search engine.
Looping through this array and finding a match resulting in $permission = true; fixes the problem.
=> Filter result on all of the permissions

phpmyfaq/admin/record.edit.php
Hello,
We've recently discovered a bug that we needed to be fixed asap, hence we already wrote the fix and would like to merge it into phpMyFAQ.
We have multiple users managing questions, and we noticed that for one account which had the right to update the visibility of a question, namely: "approverec" who could not set the visibility to visible.
Apparently checkRight failed which in turn showed me that the userId was different. I then discovered that the $user state changes when it is pulling the revision history. The last user in the foreach loop is the user that will be used from there on out. Which in turn resulted in the wrong userId being used for checkRight.
My fix is remembering the userId before entering the loop and setting the user back afterwards.
=> Return back to the original user state after rendering revisions for FAQ

phpmyfaq/inc/PMF/Search/Resultset.php
$permission would always be true due to it being overwritten by the foreach loop
=> Fixed shadow bug in Resultset

phpmyfaq/inc/PMF/Faq.php
In our production we noticed that articles within a certain category were shown on the right side when browsing an article regardless of whether the user had permission for it it or not.
Upon further inspection I noticed that the query being used did not make use of queryPermission. This pull request fixes that and the related articles on the right now shows only the articles users are allowed to see.
Whether this was intended or not, I don't know. Feel free to decline the pull request if this is the case.
=> query permissions for articles within a category

phpmyfaq/admin/assets/js/groups.js
It was possible to add a user multiple times to one group. (only in view)
Also in 3.0 the same bug. I already fixed it in my other pull request.
=> fixed jquery member view in group management

phpmyfaq/src/phpMyFAQ/Utils.php
To Test: attempt to shorten a FAQ name with 9 words.  The new link in the right panel will also be nine words long, but suffixed with a "...".  This fix makes the new link 8 words plus the "...". 
Found in 2.9; ported to 3.0.
=> one off error in shortener

phpmyfaq/src/phpMyFAQ/Instance/Elasticsearch.php
Actually ES6 does not provide the the handler "string" anymore which causes an error while creating the index. Using text or keyword is now recommended:
https://github.com/elastic/elasticsearch-dsl-py/issues/804
This fixes the search, but there is still message Elasticsearch: No such index in Admin. I'm using the most actual ES6 version (fresh install).
=> change type in mapping for ES6 Support

phpmyfaq/admin/ajax.user.php
When, in admin, you activate an user, the mail for the user with password doesn't send.
This i sbecause we change user status before activate it.
Removing the line 
`$this->setStatus('active');`
fixes this.
Hope it helps :-)
=> Fix activate user doesn't send email issue

phpmyfaq/admin/ajax.config.php
When creating a new multi-site instance, the port isn't written to the newly created database.php file.
As there seems to be no default port handling (3306) this results in an error message.
=> fix: missing dbport on multi-site creation

phpmyfaq/admin/record.questions.php
The variable `$openQuestion` does not have an element called `answer_id`. The `getAnswerId()` method should be used instead. Otherwise the php script will stop in the foreach-loop and only the first entry will be displayed.
=> Use getAnswerId() method.

phpmyfaq/ajaxservice.php
The visibility flag was mixed-up when saving questions.
=> Fix visibility flag in 'savequestion' action.

phpmyfaq/add.php
The ``add_faq`` permission should be checked in ``add.php``. Otherwise the option ``add_faq`` has no effect and users can create FAQs without permission.
=> Check add_faq permission

composer.json, composer.lock
This will make sure that…
* … `composer update` will never install dependencies that require a more recent php version.
* … `composer install` won't complain when run on php 8.
=> Set the target platform to php 7.2.0

composer.json, composer.lock
This will make sure that…
* … `composer update` will never install dependencies that require a more recent php version.
* … `composer install` won't complain when run on php 8.
=> Set the target platform to php 7.3.0

phpmyfaq/src/phpMyFAQ/Instance/Database/Pgsql.php
If table already exists a manual creation is needed (or in an update step)
=> Fixed missing seq on table creation

.github/workflows/build-php.yml, .github/workflows/codeql-analysis.yml, .github/workflows/dockerimage.yml
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
> Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
https://www.legitsecurity.com/blog/github-privilege-escalation-vulnerability
Signed-off-by: naveensrinivasan <172697+naveensrinivasan@users.noreply.github.com>
=> Set permissions for GitHub actions

docker-compose.yml
Corresponding because the MSSQL repository-url has changed
https://hub.docker.com/_/microsoft-mssql-server
=> Update MSSQL repository-url  in docker-compose.yml

phpmyfaq/contact.php, phpmyfaq/lang/language_de.php, phpmyfaq/lang/language_en.php, phpmyfaq/setup/update.php, phpmyfaq/src/phpMyFAQ/Setup/Installer.php
Hi Thorsten, 
this will add HTML-support for showing the contactInformations. It will insert a new configuration-item that can be checked if the contact informations should be formatted with HTML. 
The only problem which I see would be that the checkbox for this is not just underneath the text area for the contact-informations, but I didn't find a good solution for this. If you want to, you would have to check that again.
=> Feature request: HTML-support for contactInformations

phpmyfaq/src/phpMyFAQ/Database/Pgsql.php
PostgreSQL and MySQL have different return types when executing query.
When using PostgreSQL, some methods will generate an error because the return types do not match.
Example)
phpMyFAQ\User\CurrentUser::setRememberMe()
phpMyFAQQuestion::updateQuestionAnswer()
So we fixed it to return true if the query does not return data on successful execution.
=> fix: corrected query() response

phpmyfaq/admin/header.php
Currently, items are displayed in the side menu even if the user does not have authorization.
Therefore, we have modified the side menu so that items are not displayed if the user is not authorized.
=> Fix: admin sidemenu

phpmyfaq/admin/export.main.php
You should add this. Otherwise, no option is checked by default and an error occurs if you click on export without choosing one option.
=> fix: prevent error message

phpmyfaq/lang/language_de.php, phpmyfaq/lang/language_en.php, phpmyfaq/src/phpMyFAQ/Helper/QuestionHelper.php
The mail which is sent when a new question was added is a bit more understandable. I just added some messages.
=> Feat: Rewrite success mail for new question

phpmyfaq/assets/themes/default/templates/index.html
I would propose to delete the meta-tag which links to the phpMyFAQ-App in iOS because the app does not work for the 3.-versions.
=> fix: delete iOS-app link

phpmyfaq/src/phpMyFAQ/Entity/FaqEntity.php
When I update a FAQ, the publication end date is overwritten by the update date.
Therefore, the updated FAQ answers cannot be viewed on the public site side.
Therefore, we modified it to specify the default value.
=> Fix: faq-date-end

phpmyfaq/search.php
The search criteria for a category is lost after a paging transition on the search screen.
This phenomenon is caused by incorrect parameter names when paging.
Therefore, we have corrected the parameter names when setting paging.
=> Fix: category parameter name

phpmyfaq/api.php
Let the category owner and the admin be informed when a new question was added via REST API.
In the long run, the sendSuccessMail()-function which is in the class QuestionHelper() currently should better be integrated into Notification() to use SMTP as well if required.
=> Fix: Send notification mail for added question via api

phpmyfaq/setup/update.php, phpmyfaq/src/phpMyFAQ/Instance/Database/Mysqli.php, phpmyfaq/src/phpMyFAQ/Instance/Database/Pgsql.php, phpmyfaq/src/phpMyFAQ/Instance/Database/Sqlite3.php, phpmyfaq/src/phpMyFAQ/Instance/Database/Sqlsrv.php, phpmyfaq/src/phpMyFAQ/User/TwoFactor.php, phpmyfaq/ucp.php
This option is much easier than the other one, I'm sorry. 
Now, we can be sure that the secret coloumn is null at every time.
Fix #2517
=> Fix update problems with 2FA

phpmyfaq/admin/record.add.php
The value specified when registering the Elasticsearch index is incorrect and has been corrected.
This is the same as previously fixed here.
https://github.com/thorsten/phpMyFAQ/pull/2485
=> Fix: index registration

phpmyfaq/src/phpMyFAQ/Instance/Database/Pgsql.php
The method of specifying numeric types is not Pgsql's, and has been corrected.
=> Fix: pgsql syntax

phpmyfaq/admin/record.show.php
With Search by Solution ID turned off, I am getting an error when I enter a numerical value to search for a FAQ in the admin area.
This is because it is executing an inappropriate query syntax for the faqdata.solution_id column.
Therefore, we have modified the search to search against faqdata.solution_id only when search by solution ID is turned on.
=> Fix: admin-search-faqs

phpmyfaq/faq.php, phpmyfaq/index.php
FatalError occurs when a string is passed as the id parameter.
The reason was that a string was passed to an argument that was supposed to be numeric.
The default value for retrieving the value of the id parameter is now set to 0.
If the default value is not set, null will be set and a type error will occur.
The $id must always be numeric.
=> Fix: faqid-type-error

phpmyfaq/src/phpMyFAQ/Instance/Database/Mysqli.php
Setup was not possible, so I added a missing bracket to fix the query
=> fix: added missing bracket for setup querys

phpmyfaq/admin/login.php
Because the name attribute of "remember me" was not specified, the post value could not be obtained.
Therefore, the name attribute has been modified to be specified.
=> Fix: rememberme input field

phpmyfaq/admin/record.save.php
The revision history data is registered in the DB after inserting line break tags with "nl2br()".
However, since the data was converted by "htmlentities()" when output to the screen, it was output as a string.
"nl2br()" was removed as unnecessary.
=> Fix: remove nl2br

phpmyfaq/admin/record.edit.php
Tag data was not copied when creating a copy of the FAQ.
Therefore, it was corrected to retrieve the tag information from the source of the copy.
=> Fix: copyentry tags

phpmyfaq/admin/header.php
Currently, even if you do not have the "edit config" authority, the system information items are displayed in the side menu.
However, if the user does not have the "edit config" authority, the user will receive an error message when navigating to this item.
Therefore, we propose that the system information item should not be displayed in the side menu if the user does not have the "edit config" privilege.
=> Fix: system menu entry

phpmyfaq/admin/record.edit.php
When I create a copy of an FAQ, if the copy source has revised data, a selection item for the revised data appears on the copy creation form.
When this item is selected, the user is redirected to the original FAQ edit form.
We believe that this specification may cause users to make mistakes in making revisions.
Therefore, we have modified it so that the selection item for revision data is displayed only when editing FAQs.
=> Fix: revision display

phpmyfaq/admin/assets/src/content/tags.js, phpmyfaq/admin/record.edit.php
When I select a tag from the suggestions in the tag input field, the tag I entered disappears.
The reason is that the "data-tag-list" attribute value is acquired when selecting a suggestion.
To resolve this issue, we have modified it to retrieve the value of the input field.
With this modification, the value selected in the suggestion will be displayed in the same way as the existing behavior.
=> Fix: tag suggest

phpmyfaq/admin/record.edit.php
The escaping process for the FAQ title is duplicated, resulting in HTML entities being displayed as strings.
Therefore, we have combined the escaping processes into one.
=> Fix: duplicate htmlentities

phpmyfaq/src/phpMyFAQ/Tags.php
When I try to enter and save multiple tags with the same name, I get an SQL syntax error.
The reason is that the same id is being registered in the faqdata_tags table.
Therefore, a simple check for registered tags is now performed when registering to the DB.
=> Fix: faqdata_tags error

phpmyfaq/src/phpMyFAQ/Faq.php
The most recent commit was modified to do htmlentities() where htmlentities() was already done.
However, we do not believe that htmlentities() needs to be performed in duplicate.
Therefore, we have corrected the duplicate locations. If you have any particular reason for this, please let me know.
=> Fix: duplicate htmlentities for question

phpmyfaq/admin/stat.main.php
An error due to int type overflow was occurring in the "View Session" screen.
When there is no session file, "9999999999999999999" is specified as the initial value of timestamp.
However, if the int type exceeds the upper limit, it is interpreted as a float type.
As a result, a float type value is passed to an int type and an error occurs.
Therefore, the upper limit of the int type has been corrected so that the upper limit of the int type is passed.
=> Fix: integer overflow

phpmyfaq/admin/report.view.php
Currently, the same value is displayed for category and subcategory items in the report function.
Therefore, we have modified the report function to display the parent category name if there is a parent category.
=> Fix: report category items

phpmyfaq/assets/themes/default/templates/404.html, phpmyfaq/assets/themes/default/templates/index.html, phpmyfaq/assets/themes/default/templates/search.html, phpmyfaq/search.php
A DB error occurs when a keyword search is performed on a string of more than 255 characters.
This is because the limit of the searchterm column in the "faqsearches" table is exceeded.
Therefore, the following modifications have been made.
・Add "maxlength" to the attribute of the keyword input column.
・When acquiring the input value, the maximum length is 255 characters from the beginning.
=> Fix: searchterm maxlength

phpmyfaq/search.php
The number of rows is obtained with the num_rows property, which PostgreSQL does not have.
This property does not exist in PostgreSQL. num_rows is a property of the mysqli_result object.
Therefore, we modified it to numRows() defined in the DB class so that the number of rows can be obtained in other DBs.
=> Fix: method of getting the num rows

phpmyfaq/admin/attachments.php
Pathing the unsafe filename rendering that causing the Store XSS on attachments pages
=> Fixing unsafe render filename on attachments.php

docs/openapi.json, docs/openapi.yaml, phpmyfaq/src/phpMyFAQ/Administration/Backup.php, phpmyfaq/src/phpMyFAQ/Controller/Api/BackupController.php, phpmyfaq/src/phpMyFAQ/Enums/BackupType.php, phpmyfaq/src/phpMyFAQ/Faq/Statistics.php
If you want to integrate it, it could look like this. If not, I'll find another possibility ;-)
=> feat(api): added possibility for backup of content-folder

phpmyfaq/src/phpMyFAQ/Faq/Statistics.php
This is checked in twig; therefore this additional check isn't necessary
=> fix: show correct trending faqs on startpage
